version: "3.9"
services:

  workspace-register:
    image: harbor.stfc.ac.uk/ada-platform/workspace-register
    restart: always
    volumes:
      - type: bind
        source: ./config/workspace-register
        target: /config

  admin-panel:
    image: harbor.stfc.ac.uk/ada-platform/admin-panel
    ports:
      - 8001:81
    restart: always
    volumes:
      - type: bind
        source: ./config/admin-panel
        target: /config

